vich_uploader:
    db_driver: orm

    mappings:
        ad_image:
             uri_prefix: /images/ads
             upload_destination: '%kernel.project_dir%/public/images/ads'
             namer: Vich\UploaderBundle\Naming\UniqidNamer
